version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/k8s"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/go"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/release"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/root"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/ruby"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "build"
      include: "scope"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    allow:
      - dependency-name: "bin"
