version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/diagram"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/go"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/hbase"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/java"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/k8s"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/kotlin"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/release"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ruby"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scala"
    schedule:
      interval: "daily"
