version: "3.9"

services:
  bezeichner:
    image: alexfalkowski/bezeichner
    command: server
    restart: always
    environment:
      CONFIG_FILE: /config/bezeichner.yml
    ports:
      - "2000:8080"
      - "2001:9090"
    volumes:
      - "${PWD}/config:/config"

  standort:
    image: alexfalkowski/standort
    command: server
    restart: always
    environment:
      CONFIG_FILE: /config/standort.yml
    ports:
      - "3000:8080"
      - "3001:9090"
    volumes:
      - "${PWD}/config:/config"

  konfig:
    image: alexfalkowski/konfig
    command: server
    restart: always
    environment:
      - CONFIG_FILE=/config/konfig.yml
      - KONFIG_GIT_TOKEN=${GITHUB_TOKEN}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vault-plaintext-root-token
      - AWS_URL=http://localstack:4566
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY=access
      - AWS_SECRET_KEY=secret
    ports:
      - "4000:8080"
      - "4001:9090"
    volumes:
      - "${PWD}/config:/config"
    depends_on:
      - vault
      - localstack

  auth:
    image: alexfalkowski/auth
    command: server
    restart: always
    environment:
      CONFIG_FILE: /config/auth.yml
      AUTH_ED25519_PRIVATE_KEY: "${AUTH_ED25519_PRIVATE_KEY}"
      AUTH_RSA_PRIVATE_KEY: "${AUTH_RSA_PRIVATE_KEY}"
    ports:
      - "5000:8080"
      - "5001:9090"
    volumes:
      - "${PWD}/config:/config"

  jaegertracing:
    image: jaegertracing/all-in-one
    restart: always
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  postgres:
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:2.3
    restart: always
    ports:
      - "4566:4566"
    environment:
      SERVICES: "s3,sqs,ssm"

  vault:
    image: hashicorp/vault:1.15
    user: root
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    volumes:
      - ./vault:/etc/vault
    command: server -dev -config /etc/vault/server.hcl
    cap_add:
      - IPC_LOCK

  prometheus:
    image: prom/prometheus
    user: root
    restart: always
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/config.yml

  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 10000:3000
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  vault_data:
