services:
  postgres:
    image: docker.io/postgres:18-trixie
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: docker.io/valkey/valkey:9
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  aws:
    image: docker.io/hectorvent/floci
    restart: always
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      SERVICES: "s3,sqs,ssm"

  vault:
    image: docker.io/hashicorp/vault:1.21
    restart: always
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  lgtm:
    image: docker.io/grafana/otel-lgtm
    restart: always
    ports:
      - 127.0.0.1:10000:3000
      - 127.0.0.1:3100:3100
      - 127.0.0.1:3200:3200
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:9090:9090
    volumes:
      - lgtm_data:/data
      - ./prometheus/config.yml:/otel-lgtm/prometheus.yaml:ro

  status:
    image: docker.io/alexfalkowski/status
    command: server -config file:/etc/status/server.yaml
    restart: always
    ports:
      - "127.0.0.1:15000:8080"
      - "127.0.0.1:15001:6060"
    volumes:
      - ./status:/etc/status
    depends_on:
      - lgtm

  flipt:
    image: docker.io/flipt/flipt
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9000:9000"

volumes:
  lgtm_data:
