version: "3.9"

services:
  standort:
    image: alexfalkowski/standort
    command: server
    environment:
      CONFIG_FILE: /config/standort.yml
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - "${PWD}/config:/config"

  konfig:
    image: alexfalkowski/konfig
    command: server
    environment:
      - CONFIG_FILE=/config/konfig.yml
      - KONFIG_GIT_TOKEN=${GITHUB_TOKEN}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vault-plaintext-root-token
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - "${PWD}/config:/config"
    depends_on:
      - vault

  jaegertracing:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "6831:6831/udp"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  datadog:
    image: datadog/agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.eu
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd -broadcast-address=localhost
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd -broadcast-address=localhost --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nats:
    image: nats
    ports:
      - "4222:4222"

  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3,sqs
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  prometheus:
    image: prom/prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/config.yml
