services:
  jaegertracing:
    image: docker.io/jaegertracing/jaeger:2.2.0
    restart: always
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  postgres:
    image: docker.io/postgres:17-bullseye
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  redis:
    image: docker.io/bitnami/redis:7.4
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: test

  localstack:
    image: docker.io/localstack/localstack:4.0
    restart: always
    ports:
      - "4566:4566"
    environment:
      SERVICES: "s3,sqs,ssm"

  vault:
    image: docker.io/hashicorp/vault:1.18
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  prometheus:
    image: docker.io/prom/prometheus:v3.1.0
    user: root
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mimir
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/config.yml

  mimir:
    image: docker.io/grafana/mimir
    restart: always
    ports:
      - 9009:9009
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/mimir.yml

  grafana:
    image: docker.io/grafana/grafana-oss
    restart: always
    ports:
      - 10000:3000
    depends_on:
      - prometheus

  status:
    image: docker.io/alexfalkowski/status
    command: server
    restart: always
    environment:
      CONFIG_FILE: /config/status.yml
    ports:
      - "6000:8080"
      - "6001:9090"
    volumes:
      - "${PWD}/config:/config"

  flipt:
    image: docker.io/flipt/flipt
    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"

volumes:
  prometheus_data:
