version: "3.9"

services:
  jaegertracing:
    image: jaegertracing/all-in-one
    restart: always
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  postgres:
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: /nsqlookupd -broadcast-address=localhost
    restart: always
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq:v1.2.1
    command: /nsqd -broadcast-address=localhost --lookupd-tcp-address=nsqlookupd:4160
    restart: always
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  localstack:
    image: localstack/localstack:2.3
    restart: always
    ports:
      - "4566:4566"
    environment:
      SERVICES: "s3,sqs,ssm"

  vault:
    image: hashicorp/vault:1.15
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  prometheus:
    image: prom/prometheus
    user: root
    restart: always
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/config.yml

  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 10000:3000
    depends_on:
      - prometheus

  status:
    image: alexfalkowski/status
    command: server
    restart: always
    environment:
      CONFIG_FILE: /config/status.yml
    ports:
      - "6000:8080"
      - "6001:9090"
    volumes:
      - "${PWD}/config:/config"

volumes:
  prometheus_data:
