version: 2.1

setup: true

orbs:
  path_filtering: circleci/path-filtering@3.0.0

workflows:
  filter:
    jobs:
      - path_filtering/filter:
          mapping: |
            .circleci/.* docker true
            Makefile docker true
            make/.* docker true
            scripts/.* docker true
            docker/.* docker true

            .circleci/.* stack true
            Makefile stack true
            compose.yml stack true
            grafana/.* stack true
            otelcol/.* stack true
            prometheus/.* stack true
            status/.* stack true

            .circleci/.* go true
            Makefile go true
            make/.* go true
            scripts/.* go true
            go/.* go true

            .circleci/.* k8s true
            Makefile k8s true
            make/.* k8s true
            scripts/.* k8s true
            k8s/.* k8s true

            .circleci/.* release true
            Makefile release true
            make/.* release true
            scripts/.* release true
            release/.* release true

            .circleci/.* root true
            Makefile root true
            make/.* root true
            scripts/.* root true
            root/.* root true

            .circleci/.* ruby true
            Makefile ruby true
            make/.* ruby true
            scripts/.* ruby true
            ruby/.* ruby true
          base-revision: origin/master
          resource_class: large
