version: 2.1

parameters:
  root:
    type: boolean
    default: false

jobs:
  lint:
    docker:
      - image: alexfalkowski/docker:1.20
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make scripts-lint
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.24
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make pull
      - run: release
    resource_class: large

  root-lint:
    docker:
      - image: alexfalkowski/docker:1.20
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make -C root lint-docker
    resource_class: large
  root-build:
    docker:
      - image: cimg/base:2025.06-24.04
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root build-docker
    resource_class: large
  root-push:
    docker:
      - image: cimg/base:2025.06-24.04
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root push-docker
    resource_class: large
  root-build-arm:
    docker:
      - image: cimg/base:2025.06-24.04
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root build-docker
    resource_class: arm.medium
  root-push-arm:
    docker:
      - image: cimg/base:2025.06-24.04
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root push-docker
    resource_class: arm.medium

workflows:
  lint:
    jobs:
      - lint
      - release:
          requires:
            - lint
          filters:
            branches:
              only: master

  root:
    when: << pipeline.parameters.root >>
    jobs:
      - root-lint
      - root-build:
          context: docker
          filters:
            branches:
              ignore: master
      - root-build-arm:
          context: docker
          filters:
            branches:
              ignore: master
      - root-push:
          context: docker
          filters:
            branches:
              only: master
      - root-push-arm:
          context: docker
          filters:
            branches:
              only: master
