version: 2.1

parameters:
  docker:
    type: boolean
    default: false
  go:
    type: boolean
    default: false
  k8s:
    type: boolean
    default: false
  monitoror:
    type: boolean
    default: false
  root:
    type: boolean
    default: false

jobs:
  lint:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make scripts-lint
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.24
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make pull
      - run: release
    resource_class: large

  docker-lint:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make -C docker lint-docker
    resource_class: large
  docker-build-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C docker platform=amd64 build-docker
    resource_class: large
  docker-push-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C docker platform=amd64 push-docker
    resource_class: large
  docker-build-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C docker platform=arm64 build-docker
    resource_class: arm.medium
  docker-push-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C docker platform=arm64 push-docker
    resource_class: arm.medium
  docker-manifest:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C docker manifest-docker
    resource_class: large

  go-lint:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make -C go lint-docker
    resource_class: large
  go-build-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C go platform=amd64 build-docker
    resource_class: large
  go-push-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C go platform=amd64 push-docker
    resource_class: large
  go-build-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C go platform=arm64 build-docker
    resource_class: arm.medium
  go-push-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C go platform=arm64 push-docker
    resource_class: arm.medium
  go-manifest:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C go manifest-docker
    resource_class: large

  k8s-lint:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make -C k8s lint-docker
    resource_class: large
  k8s-build-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C k8s platform=amd64 build-docker
    resource_class: large
  k8s-push-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C k8s platform=amd64 push-docker
    resource_class: large
  k8s-build-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C k8s platform=arm64 build-docker
    resource_class: arm.medium
  k8s-push-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C k8s platform=arm64 push-docker
    resource_class: arm.medium
  k8s-manifest:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C k8s manifest-docker
    resource_class: large

  monitoror-lint:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make -C monitoror lint-docker
    resource_class: large
  monitoror-build-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C monitoror platform=amd64 build-docker
    resource_class: large
  monitoror-push-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C monitoror platform=amd64 push-docker
    resource_class: large
  monitoror-manifest:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C monitoror manifest-docker
    resource_class: large

  root-lint:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make -C root lint-docker
    resource_class: large
  root-build-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root platform=amd64 build-docker
    resource_class: large
  root-push-amd64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root platform=amd64 push-docker
    resource_class: large
  root-build-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    working_directory: ~/docker
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root platform=arm64 build-docker
    resource_class: arm.medium
  root-push-arm64:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root platform=arm64 push-docker
    resource_class: arm.medium
  root-manifest:
    docker:
      - image: alexfalkowski/docker:1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make -C root manifest-docker
    resource_class: large

workflows:
  lint:
    jobs:
      - lint
      - release:
          requires:
            - lint
          filters:
            branches:
              only: master

  docker:
    when: << pipeline.parameters.docker >>
    jobs:
      - docker-lint
      - docker-build-amd64:
          context: docker
          filters:
            branches:
              ignore: master
      - docker-build-arm64:
          context: docker
          filters:
            branches:
              ignore: master
      - docker-push-amd64:
          context: docker
          filters:
            branches:
              only: master
      - docker-push-arm64:
          context: docker
          filters:
            branches:
              only: master
      - docker-manifest:
          context: docker
          requires:
            - docker-push-amd64
            - docker-push-arm64
          filters:
            branches:
              only: master

  go:
    when: << pipeline.parameters.go >>
    jobs:
      - go-lint
      - go-build-amd64:
          context: docker
          filters:
            branches:
              ignore: master
      - go-build-arm64:
          context: docker
          filters:
            branches:
              ignore: master
      - go-push-amd64:
          context: docker
          filters:
            branches:
              only: master
      - go-push-arm64:
          context: docker
          filters:
            branches:
              only: master
      - go-manifest:
          context: docker
          requires:
            - go-push-amd64
            - go-push-arm64
          filters:
            branches:
              only: master

  k8s:
    when: << pipeline.parameters.k8s >>
    jobs:
      - k8s-lint
      - k8s-build-amd64:
          context: docker
          filters:
            branches:
              ignore: master
      - k8s-build-arm64:
          context: docker
          filters:
            branches:
              ignore: master
      - k8s-push-amd64:
          context: docker
          filters:
            branches:
              only: master
      - k8s-push-arm64:
          context: docker
          filters:
            branches:
              only: master
      - k8s-manifest:
          context: docker
          requires:
            - k8s-push-amd64
            - k8s-push-arm64
          filters:
            branches:
              only: master

  monitoror:
    when: << pipeline.parameters.monitoror >>
    jobs:
      - monitoror-lint
      - monitoror-build-amd64:
          context: docker
          filters:
            branches:
              ignore: master
      - monitoror-push-amd64:
          context: docker
          filters:
            branches:
              only: master
      - k8s-manifest:
          context: docker
          requires:
            - monitoror-push-amd64
          filters:
            branches:
              only: master

  root:
    when: << pipeline.parameters.root >>
    jobs:
      - root-lint
      - root-build-amd64:
          context: docker
          filters:
            branches:
              ignore: master
      - root-build-arm64:
          context: docker
          filters:
            branches:
              ignore: master
      - root-push-amd64:
          context: docker
          filters:
            branches:
              only: master
      - root-push-arm64:
          context: docker
          filters:
            branches:
              only: master
      - root-manifest:
          context: docker
          requires:
            - root-push-amd64
            - root-push-arm64
          filters:
            branches:
              only: master
