global:
  scrape_interval: 1s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'standort'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.containers.internal:3000']
  - job_name: 'konfig'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.containers.internal:4000']
  - job_name: 'bezeichner'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.containers.internal:2000']
  - job_name: 'auth'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.containers.internal:5000']
  - job_name: 'status'
    scrape_interval: 5s
    static_configs:
      - targets: ['status:8080']
