{
 "title": "Delivery",
 "description": "Delivery telemetry emitted.",
 "tags": [
  "delivery",
  "oteldel"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values({__name__=~\"cicd_pipeline_run_duration_seconds_bucket|cicd_pipeline_run_errors_total|cicd_artifact_publish_count_total|cicd_deployment_request_count_total\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Duration (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (cicd_pipeline_name, cicd_pipeline_result) (rate(cicd_pipeline_run_duration_seconds_sum{service_name=~\"$service\"}[5m])) / clamp_min(sum by (cicd_pipeline_name, cicd_pipeline_result) (rate(cicd_pipeline_run_duration_seconds_count{service_name=~\"$service\"}[5m])), 1)",
     "legendFormat": "{{cicd_pipeline_name}} {{cicd_pipeline_result}}"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cicd_pipeline_name, error_type) (rate(cicd_pipeline_run_errors_total{service_name=~\"$service\"}[5m]))",
     "legendFormat": "{{cicd_pipeline_name}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Artifact Publish Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(cicd_artifact_publish_count_total{service_name=~\"$service\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Deployment Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(cicd_deployment_request_count_total{service_name=~\"$service\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Deployment Request Duration (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(cicd_deployment_request_duration_seconds_sum{service_name=~\"$service\"}[5m])) / clamp_min(sum by (result) (rate(cicd_deployment_request_duration_seconds_count{service_name=~\"$service\"}[5m])), 1)",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}