build:
	docker build -t alexfalkowski/java:15 .

push: build
	docker push alexfalkowski/java:15

lint:
	docker run --rm -i hadolint/hadolint < Dockerfile

lint:
	docker run --rm -i hadolint/hadolint < Dockerfile
