environment: production
debug:
  port: 6060
cache:
  ristretto:
    num_counters: 10000000
    max_cost: 100000000
    buffer_items: 64
casbin:
  model: |
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
  policy: |
    p, konfig, standort, get-location
health:
  duration: 1s
  timeout: 1s
key:
  ed25519:
    public: S/GinVVEvin0yfP3buKjs7SpFzbaVeTforBh6eYiaF4=
    private: env:AUTH_ED25519_PRIVATE_KEY
  rsa:
    public: MIICCgKCAgEAylHb4j6LrAIsnrjS0jLVERMMvmpfuqnqVPHq0ifAxhs60fL6WV+b4spjlHf3+/DtXUVHI1M9entD+RGy7jqRaCkhKJuH+p/SnkUXwn0iQnw7MpmK5hjpeaBHm8lYfOsd3BX7Jyg1nduTnSvnIlUIIv+bBuFggox2IZVD++uy2Qbgkym9Hb6F03L3XeGOupIeQnQQ/sSboTzF3ghz+tMB6OkZxr1MVFdl0ABIkYUoxq7gq2D6GtqdYvmx5l2LKaACe4WGiPdghaeu5YUolsyCg8SJ/R4gxIAkMYJmb7RMefGn40CYyPl9lXgHshZK/RG/PhA8WZvG7QmiJWe/Jf5G30ga6Mzm0pGG7skdgWfnsCiGyRYTZowf8MAQcFbPfjPXTqTVRA8aPFq8AVLyTCXN7v6bOhkXwOyGRIuhdqH5EkYQ10kL83CVnHJ8Byr38gv411AIekTJs9rZGfSYgsSkHKcMmOP9zudgek/Wqgct+bv1noAXhgSvvnt6ocIt5hF1W7DqTfvpuimiMZh6hsTnB7GW8rm1YJmKrLqtjWCV9zJuUavAba6zrP37rkDXcpy3CLe8sevHSOm/VPdtBoC5DfvRmMio9omAwAiUVq5gSvPAtthEtCrrnZGZdEo+KmNveFvOyyFrhDxcHwEgjyOhOcLoUorb2Y+bhYLeqBqcyg0CAwEAAQ==
    private: env:AUTH_RSA_PRIVATE_KEY
server:
  v1:
    issuer: https://auth.falkowski.io
    admins:
      - id: su
        hash: $2a$10$ivuAL1QNtguC.IFqGpMT8.IjpyHinSmCdZWJCCDGXRCZmqTOsXVK2
    services:
      - id: e1602e185cba2a90d8bbcfc3f3c5530c
        name: konfig
        hash: $2a$10$Qkp5LOsT4TfXAAwMvisK8eYjTZPvTQUvGSkY78p7etFnosLrGJeU2
        duration: 24h
      - id: 7e8c24379930d107b2d281aa23247092
        name: standort
        hash: $2a$10$MTGlGTx4s4Ykg2X01jZk/.6ly1Fbv5wFqH/LfBMNmoTmEka09OS.K
        duration: 24h
telemetry:
  logger:
    enabled: true
    level: warn
  tracer:
    enabled: true
    host: localhost:4318
    secure: false
transport:
  http:
    port: 5000
    security:
      enabled: true
      cert_file: config/certs/cert.pem
      key_file: config/certs/key.pem
      client_cert_file: config/certs/client-cert.pem
      client_key_file: config/certs/client-key.pem
    user_agent: "Auth-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 5001
    security:
      enabled: true
      cert_file: config/certs/cert.pem
      key_file: config/certs/key.pem
      client_cert_file: config/certs/client-cert.pem
      client_key_file: config/certs/client-key.pem
    user_agent: "Auth-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
