environment: production
mapper:
  identifiers:
    req1: resp1
    req2: resp2
generator:
  applications:
    - name: uuid
      kind: uuid
    - name: ksuid
      kind: ksuid
    - name: ulid
      kind: ulid
    - name: xid
      kind: xid
    - name: nanoid
      kind: nanoid
    - name: snowflake
      kind: snowflake
health:
  duration: 1s
  timeout: 1s
telemetry:
  logger:
    level: error
  tracer:
    host: jaegertracing:4318
    secure: false
transport:
  http:
    port: 8080
    user_agent: "Bezeichner-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 9090
    user_agent: "Bezeichner-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
