environment: production
debug:
  port: 6060
mapper:
  identifiers:
    req1: resp1
    req2: resp2
generator:
  applications:
    - name: uuid
      kind: uuid
    - name: ksuid
      kind: ksuid
    - name: ulid
      kind: ulid
    - name: xid
      kind: xid
    - name: nanoid
      kind: nanoid
    - name: snowflake
      kind: snowflake
    - name: typeid
      kind: typeid
health:
  duration: 1s
  timeout: 1s
telemetry:
  logger:
    level: warn
  tracer:
    host: localhost:4318
    secure: false
transport:
  http:
    port: 2000
    user_agent: "Bezeichner-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 2001
    user_agent: "Bezeichner-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
