health:
  duration: 30s
  timeout: 1s
source:
  kind: git
  git:
    url: https://github.com/alexfalkowski/app-config
    dir: /tmp/app-config
telemetry:
  tracer:
    host: jaegertracing:4318
    secure: false
transport:
  http:
    port: 8080
    user_agent: "Konfig-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 9090
    user_agent: "Konfig-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
