auth:
  client:
    v1:
      host: localhost:5001
      timeout: 1s
environment: production
debug:
  port: 6060
health:
  duration: 30s
  timeout: 1s
source:
  kind: git
  git:
    url: https://github.com/alexfalkowski/app-config
    dir: /tmp/app-config
telemetry:
  logger:
    level: warn
  tracer:
    host: localhost:4318
    secure: false
transport:
  http:
    port: 4000
    user_agent: "Konfig-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 4001
    user_agent: "Konfig-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
