health:
  duration: 30s
  timeout: 1s
source:
  kind: git
  git:
    url: https://github.com/alexfalkowski/app-config
    dir: /tmp/app-config
otel:
  kind: jaeger
  host: jaegertracing:6831
transport:
  port: 8080
  http:
    user_agent: "Konfig-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    user_agent: "Konfig-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
