client:
  v1:
    host: localhost:12000
    user_agent: "Konfig-client/1.0 gRPC/1.0"
    retry:
      timeout: 10s
      attempts: 3
debug:
  port: 6060
environment: development
health:
  duration: 1s
  timeout: 1s
source:
  kind: git
  git:
    url: https://github.com/alexfalkowski/app-config
    dir: tmp/app-config
telemetry:
  logger:
    enabled: true
    level: info
  tracer:
    enabled: true
    host: localhost:4318
    secure: false
transport:
  http:
    enabled: true
    port: 11000
    user_agent: "Konfig-server/1.0 HTTP/1.0"
    retry:
      timeout: 10s
      attempts: 3
  grpc:
    enabled: true
    port: 12000
    user_agent: "Konfig-server/1.0 gRPC/1.0"
    retry:
      timeout: 10s
      attempts: 3
