health:
  duration: 30s
  timeout: 1s
runtime: container
server:
  v1:
    provider:
      ssm:
        access: access
        secret: secret
        region: eu-west-1
        url: http://localstack:4566
    source:
      kind: git
      git:
        url: https://github.com/alexfalkowski/app-config
        dir: /tmp/app-config
trace:
  opentracing:
    kind: jaeger
    host: jaegertracing:6831
transport:
  port: 8080
  http:
    user_agent: "Konfig-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    user_agent: "Konfig-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
