environment: production
debug:
  port: 6060
health:
  duration: 1s
  timeout: 1s
migrate:
  databases:
    -
      name: postgres
      source: file://config/migrations
      url: postgres://test:test@localhost:5432/test?sslmode=disable
telemetry:
  logger:
    level: warn
  tracer:
    host: localhost:4318
    secure: false
transport:
  http:
    port: 7000
    user_agent: "Migrieren-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 7001
    user_agent: "Migrieren-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
