environment: development
debug:
  port: 6060
client:
  v1:
    host: localhost:12000
    user_agent: "Migrieren-client/1.0 gRPC/1.0"
    timeout: 1s
    retry:
      timeout: 2s
      attempts: 3
    database: postgres
    version: 1
health:
  duration: 1s
  timeout: 1s
migrate:
  databases:
    -
      name: postgres
      source: file://test/migrations
      url: pgx5://test:test@localhost:5432/test?sslmode=disable
telemetry:
  logger:
    enabled: true
    level: info
  tracer:
    enabled: true
    host: localhost:4318
    secure: false
transport:
  http:
    enabled: true
    port: 11000
    user_agent: "Migrieren-server/1.0 HTTP/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    enabled: true
    port: 12000
    user_agent: "Migrieren-server/1.0 gRPC/1.0"
    retry:
      timeout: 2s
      attempts: 3
