health:
  duration: 1s
  timeout: 1s
location:
  ip:
    type: ip2location
trace:
  opentracing:
    type: jaeger
    host: jaegertracing:6831
transport:
  port: 8080
  http:
    user_agent: "Standort-server/1.0 http/1.0"
    retry:
      timeout: 2s
      attempts: 3
  grpc:
    user_agent: "Standort-server/1.0 grpc/1.0"
    retry:
      timeout: 2s
      attempts: 3
