debug:
  timeout: 10s
environment: development
health:
  duration: 1s
  timeout: 1s
telemetry:
  logger:
    level: info
  metrics:
    kind: prometheus
transport:
  http:
    retry:
      attempts: 3
      backoff: 100ms
      timeout: 10s
    timeout: 5s
