#!/usr/bin/env bash
# shellcheck disable=SC2155

set -eo pipefail

make pull

if [ -f ".cd" ]; then
  readonly message=$(git log --pretty=format:"%s" -n 1)
  if [[ "$message" =~ ^chore* ]]; then
    readonly name=$(basename "$PWD")
    readonly version="$(git tag | sort -V | tail -1)"
    readonly desc="https://github.com/alexfalkowski/$name/releases/tag/$version"

    # Get the repo.
    git clone git@github.com:alexfalkowski/infraops.git
    (cd infraops && git submodule sync && git submodule update --init)

    # Bump the version and raise a PR.
    (cd infraops && make name="$name" new-release && bump -n "$name" -v "${version:1}" -p area/apps/apps.pbtxt && make msg="upgraded to $version" desc="${desc}" ready)
    rm -rf infraops
  fi
fi
