#!/usr/bin/env bash
# shellcheck disable=SC2155

set -eo pipefail

if [ -f ".cd" ]; then
  readonly version_file="${APP_VERSION_FILE:-/tmp/workspace/release-version.txt}"
  if [[ -f "$version_file" ]]; then
    readonly name=$(basename "$PWD")
    readonly version="$(cat "$version_file")"
    readonly desc="https://github.com/alexfalkowski/$name/releases/tag/$version"

    # Get the repo.
    git clone --filter=blob:none git@github.com:alexfalkowski/infraops.git
    (cd infraops && git submodule sync && git submodule update --init)

    # Bump the version and raise a PR.
    (cd infraops && make name="$name" new-release && bump -n "$name" -v "${version:1}" && make msg="upgraded to $version" desc="${desc}" ready)
    rm -rf infraops
  fi
fi
