#!/usr/bin/env bash
# shellcheck disable=SC2155

set -eo pipefail

readonly releaser=$(find . -name "*goreleaser*" -not -path "*vendor*")

if [ -n "$releaser" ]; then
  readonly message=$(git log --pretty=format:"%s" -n 1)
  readonly message_pattern='^(feat|fix)(\([^)]*\))?!?:'

  if [[ "$message" =~ $message_pattern ]]; then
    goreleaser release
  fi
fi
