#!/bin/bash
# shellcheck disable=SC2155

set -eo pipefail

# Release with uplift.
uplift release --config-dir /etc/uplift

readonly releaser=$(find . -name "*goreleaser*" -not -path "*vendor*")

if [ -n "$releaser" ]; then
  readonly message=$(git log --pretty=format:"%s" -n 1)

  if [[ "$message" =~ ^chore* ]]; then
      goreleaser release
  fi
fi
