#!/usr/bin/env bash
# shellcheck disable=SC2155

set -eo pipefail

readonly version_file="${APP_VERSION_FILE:-/tmp/workspace/release-version.txt}"

mkdir -p "$(dirname "$version_file")"
rm -f "$version_file"

readonly previous_version="$(git tag --points-at HEAD | sort -V | tail -1)"

uplift release --skip-changelog --config-dir /etc/uplift

readonly version="$(git tag --points-at HEAD | sort -V | tail -1)"

if [[ -n "$version" && "$version" != "$previous_version" ]]; then
  echo "$version" > "$version_file"
fi
