#!/usr/bin/env bash
# shellcheck disable=SC2155

set -eo pipefail

readonly version_file="${APP_VERSION_FILE:-/tmp/workspace/release-version.txt}"
readonly message_pattern='^chore*'

mkdir -p "$(dirname "$version_file")"
rm -f "$version_file"

uplift release --skip-changelog --config-dir /etc/uplift

readonly message=$(git log --pretty=format:"%s" -n 1)

if [[ "$message" =~ $message_pattern ]]; then
  git tag | sort -V | tail -1 > "$version_file"
fi
