#!/usr/bin/env bash

set -eo pipefail

if command -v podman &>/dev/null; then
  podman image prune -a -f
  exit 0
fi

if command -v docker &>/dev/null; then
  docker image prune -a -f
  exit 0
fi

exit 1
