#!/usr/bin/env bash

set -e

readonly service=$1
readonly code_path=".."
readonly service_path="$code_path/$service"

# Compile the service.
(cd "$service_path" && git pull --rebase && make go-dep && make build)

# Copy the service.
cp "$service_path/$service" bin
