#!/usr/bin/env bash

set -eo pipefail

if command -v podman &> /dev/null
then
    podman-compose "$@"
    exit 0
fi

if command -v docker &> /dev/null
then
    docker compose "$@"
    exit 0
fi

exit 1
