#!/usr/bin/env bash

set -eo pipefail

if command -v podman &>/dev/null; then
  exec podman compose "$@"
fi

if command -v docker &>/dev/null; then
  exec docker compose "$@"
fi

echo "expected podman or docker in PATH" >&2
exit 1
