#!/usr/bin/env bash

set -euo pipefail

# Run hadolint on all Dockerfiles
while IFS= read -r -d '' dockerfile; do
  dir="$(dirname "$dockerfile")"
  echo "hadolint: $dockerfile"
  (
    cd "$dir"
    hadolint Dockerfile
  )
done < <(find . -path ./bin -prune -o -type f -name 'Dockerfile' -print0)

# Shellcheck all scripts
echo "shellcheck: all scripts"
shellcheck scripts/lint scripts/clean scripts/compose scripts/install-image-tool \
  release/deploy release/package release/version \
  docker/scripts/install-image-tool.d/* \
  go/scripts/install-image-tool.d/* \
  k8s/scripts/install-image-tool.d/* \
  release/scripts/install-image-tool.d/* \
  root/scripts/install-image-tool.d/* \
  ruby/scripts/install-image-tool.d/*
