#!/usr/bin/env bash

set -euo pipefail

# Run hadolint on all Dockerfiles
while IFS= read -r -d '' dockerfile; do
  dir="$(dirname "$dockerfile")"
  echo "hadolint: $dockerfile"
  (
    cd "$dir"
    hadolint Dockerfile
  )
done < <(find . -path ./bin -prune -o -type f -name 'Dockerfile' -print0)

# Shellcheck all scripts
echo "shellcheck: all scripts"
shellcheck scripts/lint scripts/clean scripts/compose release/deploy release/package release/version
