#!/usr/bin/env bash

set -e

declare -a arr=("auth" "bezeichner" "standort" "konfig" "migrieren")

for svc in "${arr[@]}"
do
  printf "compiling %s...\n\n" "$svc"

  ./scripts/compile "$svc"

  printf "\ndone %s\n\n" "$svc"
done
