#!/bin/bash
set -euo pipefail

# Verify standort works.
curl -sf http://localhost:3000/v1/location/ip/95.91.246.242 | grep '"continent":"EU"'
curl -sf http://localhost:3000/v1/location/lat/52.515816/lng/13.454293 | grep '"continent":"EU"'
curl -sf "http://localhost:3000/v2/location?point.lat=52.515816&point.lng=13.454293" | grep '"continent":"EU"'

# Verify konfig works.
curl -sf http://localhost:4000/v1/config/test/v1.8.0/staging/eu/de/server | grep '"version":"v1.8.0"'
